#!/usr/bin/env python3
# ==============================================================================
# apply_zenoh_hook.py
#
# Inject a TCG quantum hook into QEMU's cpu-exec.c.
#
# QEMU does not expose a native plugin API to hook into the main translation 
# block (TB) execution loop (`cpu_exec`). In order to allow external QOM modules
# (like the zenoh clock sync from FirmwareStudio) to cooperatively halt QEMU 
# at translation block boundaries, we must inject a global function pointer.
#
# This script is idempotent: it parses `accel/tcg/cpu-exec.c`, finds the 
# execution loop, and safely AST-injects a call to `qenode_tcg_quantum_hook`.
# ==============================================================================

import os
import sys

def write_if_changed(path, content):
    """Write content to path only if it differs. Returns True if written."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path):
        with open(path) as f:
            if f.read() == content:
                return False
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path)}")
    return True

def patch_file(path, marker, insertion, after=True):
    with open(path) as f:
        content = f.read()
    if marker not in content:
        print(f"  WARNING: marker not found in {os.path.relpath(path)}: {marker!r}")
        return False
    if insertion.strip() in content:
        return False
    if after:
        content = content.replace(marker, marker + insertion, 1)
    else:
        content = content.replace(marker, insertion + marker, 1)
    with open(path, "w") as f:
        f.write(content)
    print(f"  patched {os.path.relpath(path)}")
    return True

def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <qemu-source-dir>")
        sys.exit(1)

    qemu = os.path.abspath(sys.argv[1])
    
    # 1. Create include/qenode/hooks.h
    hooks_h = os.path.join(qemu, "include", "qenode", "hooks.h")
    
    hooks_h_content = """/* Generated by apply_zenoh_hook.py */
#ifndef QENODE_HOOKS_H
#define QENODE_HOOKS_H

#include "hw/core/cpu.h"

extern void (*qenode_tcg_quantum_hook)(CPUState *cpu);

#endif
"""
    
    write_if_changed(hooks_h, hooks_h_content)

    cpu_exec_c = os.path.join(qemu, "accel", "tcg", "cpu-exec.c")
    
    # 2. Add include to cpu-exec.c
    marker0 = '#include "internal-common.h"'
    insertion0 = '\n#include "qenode/hooks.h"'
    patch_file(cpu_exec_c, marker0, insertion0, after=True)

    # 3. Add the function pointer definition
    marker1 = "/* main execution loop */"
    insertion1 = "\nvoid (*qenode_tcg_quantum_hook)(CPUState *cpu) = NULL;\n"
    patch_file(cpu_exec_c, marker1, insertion1, after=True)
    
    # 4. Add the hook invocation in cpu_exec_loop
    # We use a more specific marker to ensure correct placement and indentation
    marker2 = "while (!cpu_handle_interrupt(cpu, &last_tb)) {"
    # Indentation: 12 spaces for the 'if', 16 for the call (while is at 8)
    insertion2 = "\n            if (qenode_tcg_quantum_hook) {\n                qenode_tcg_quantum_hook(cpu);\n            }\n"
    patch_file(cpu_exec_c, marker2, insertion2, after=True)

if __name__ == "__main__":
    main()
