#!/usr/bin/env python3
import sys

import yaml


def parse_yaml(filepath):
    with open(filepath, "r") as f:
        data = yaml.safe_load(f)

    print(f"/* Generated by usd_to_virtmcu.py from {filepath} */")
    print("#pragma once\n")
    print("#include <cstdint>\n")
    print("namespace virtmcu {")
    print("namespace address_map {\n")

    if "peripherals" in data:
        for periph in data["peripherals"]:
            name = periph.get("name", "UNKNOWN")
            addr = periph.get("address", "0x0")
            safe_name = name.replace("-", "_").upper()
            print(f"    constexpr uint64_t {safe_name}_BASE = {addr};")

    print("\n} // namespace address_map")
    print("} // namespace virtmcu")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <schema.yaml>")
        sys.exit(1)

    parse_yaml(sys.argv[1])
