# =============================================================================
# vproto.py - AUTO-GENERATED BY proto_gen.py
# DO NOT EDIT DIRECTLY. Edit hw/misc/virtmcu_proto.h instead.
# =============================================================================

import struct
from dataclasses import dataclass

VIRTMCU_PROTO_MAGIC = 1447904085
VIRTMCU_PROTO_VERSION = 1
MMIO_REQ_READ = 0
MMIO_REQ_WRITE = 1
SYSC_MSG_RESP = 0
SYSC_MSG_IRQ_SET = 1
SYSC_MSG_IRQ_CLEAR = 2

FMT_VIRTMCU_HANDSHAKE = '<II'
SIZE_VIRTMCU_HANDSHAKE = struct.calcsize(FMT_VIRTMCU_HANDSHAKE)

@dataclass
class VirtmcuHandshake:
    magic: int  # uint32_t
    version: int  # uint32_t

    @classmethod
    def unpack(cls, data: bytes) -> 'VirtmcuHandshake':
        if len(data) != SIZE_VIRTMCU_HANDSHAKE:
            raise ValueError(f"Expected {SIZE_VIRTMCU_HANDSHAKE} bytes for VirtmcuHandshake, got {len(data)}")
        unpacked = struct.unpack(FMT_VIRTMCU_HANDSHAKE, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_VIRTMCU_HANDSHAKE, self.magic, self.version)

FMT_MMIO_REQ = '<BBHIQQQ'
SIZE_MMIO_REQ = struct.calcsize(FMT_MMIO_REQ)

@dataclass
class MmioReq:
    type: int  # uint8_t
    size: int  # uint8_t
    reserved1: int  # uint16_t
    reserved2: int  # uint32_t
    vtime_ns: int  # uint64_t
    addr: int  # uint64_t
    data: int  # uint64_t

    @classmethod
    def unpack(cls, data: bytes) -> 'MmioReq':
        if len(data) != SIZE_MMIO_REQ:
            raise ValueError(f"Expected {SIZE_MMIO_REQ} bytes for MmioReq, got {len(data)}")
        unpacked = struct.unpack(FMT_MMIO_REQ, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_MMIO_REQ, self.type, self.size, self.reserved1, self.reserved2, self.vtime_ns, self.addr, self.data)

FMT_SYSC_MSG = '<IIQ'
SIZE_SYSC_MSG = struct.calcsize(FMT_SYSC_MSG)

@dataclass
class SyscMsg:
    type: int  # uint32_t
    irq_num: int  # uint32_t
    data: int  # uint64_t

    @classmethod
    def unpack(cls, data: bytes) -> 'SyscMsg':
        if len(data) != SIZE_SYSC_MSG:
            raise ValueError(f"Expected {SIZE_SYSC_MSG} bytes for SyscMsg, got {len(data)}")
        unpacked = struct.unpack(FMT_SYSC_MSG, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_SYSC_MSG, self.type, self.irq_num, self.data)

